const Discord = require("discord.js");
const superagent = require("superagent");

module.exports.run = async (bot,message,args) => {

  if(!message.channel.nsfw) return message.channel.send("Please fap in a NSFW channel, not here.");

  let porngif = [
    "https://cdn.boob.bot/Gifs/17B8.gif",
    "https://cdn.boob.bot/Gifs/15CC.gif",
    "https://cdn.boob.bot/Gifs/1889.gif",
    "https://cdn.boob.bot/Gifs/18F2.gif",
    "https://cdn.boob.bot/Gifs/1743.gif",
    "https://cdn.boob.bot/Gifs/1814.gif",
    "https://cdn.boob.bot/Gifs/1771.gif",
    "https://cdn.boob.bot/Gifs/1735.gif",
    "https://cdn.boob.bot/Gifs/1893.gif",
    "https://cdn.boob.bot/Gifs/175D.gif",
    "https://cdn.boob.bot/Gifs/19B3.gif",
    "https://cdn.boob.bot/Gifs/1925.gif",
    "https://cdn.boob.bot/Gifs/1667.gif",
    "https://cdn.boob.bot/Gifs/1693.gif",
    "https://cdn.boob.bot/Gifs/18C9.gif",
    "https://cdn.boob.bot/Gifs/1696.gif",
    "https://cdn.boob.bot/Gifs/17AE.gif",
    "https://cdn.boob.bot/Gifs/16AE.gif",
    "https://cdn.boob.bot/Gifs/1932.gif",
    "https://cdn.boob.bot/Gifs/16F5.gif",
    "https://cdn.boob.bot/Gifs/18E3.gif",
    "https://cdn.boob.bot/Gifs/1959.gif",
    "https://cdn.boob.bot/Gifs/15F7.gif",
    "https://cdn.boob.bot/Gifs/165C.gif",
    "https://cdn.boob.bot/Gifs/183E.gif",
    "https://cdn.boob.bot/Gifs/15BE.gif",
    "https://cdn.boob.bot/Gifs/1686.gif",
    "https://cdn.boob.bot/Gifs/184C.gif",
    "https://cdn.boob.bot/Gifs/18AA.gif",
    "https://cdn.boob.bot/Gifs/1731.gif",
    "https://cdn.boob.bot/Gifs/1767.gif",
    "https://cdn.boob.bot/Gifs/1776.gif",
    "https://cdn.boob.bot/Gifs/1742.gif",
    "https://cdn.boob.bot/Gifs/191A.gif",
    "https://cdn.boob.bot/Gifs/16B4.gif",
    "https://cdn.boob.bot/Gifs/1759.gif",
    "https://cdn.boob.bot/Gifs/175A.gif",
    "https://cdn.boob.bot/Gifs/18D0.gif",
    "https://cdn.boob.bot/Gifs/186A.gif",
    "https://cdn.boob.bot/Gifs/1655.gif",
    "https://cdn.boob.bot/Gifs/18C5.gif",
    "https://cdn.boob.bot/Gifs/1687.gif",
    "https://cdn.boob.bot/Gifs/1737.gif",
    "https://cdn.boob.bot/Gifs/199C.gif",
    "https://cdn.boob.bot/Gifs/199F.gif",
    "https://cdn.boob.bot/Gifs/1782.gif",
    "https://cdn.boob.bot/Gifs/166D.gif",
    "https://cdn.boob.bot/Gifs/1860.gif",
    "https://cdn.boob.bot/Gifs/1765.gif",
    "https://cdn.boob.bot/Gifs/17FC.gif",
    "https://cdn.boob.bot/Gifs/1744.gif",
    "https://cdn.boob.bot/Gifs/17B0.gif",
    "https://cdn.boob.bot/Gifs/1915.gif",
    "https://cdn.boob.bot/Gifs/171D.gif",
    "https://cdn.boob.bot/Gifs/15FF.gif",
    "https://cdn.boob.bot/Gifs/1685.gif",
    "https://cdn.boob.bot/Gifs/164F.gif",
    "https://cdn.boob.bot/Gifs/16F6.gif",
    "https://cdn.boob.bot/Gifs/1803.gif",
    "https://cdn.boob.bot/Gifs/199C.gif",
    "https://cdn.boob.bot/Gifs/176F.gif",
    "https://cdn.boob.bot/Gifs/1966.gif",
    "https://cdn.boob.bot/Gifs/1728.gif",
    "https://cdn.boob.bot/Gifs/1621.gif",
    "https://cdn.boob.bot/Gifs/16BE.gif",
    "https://cdn.boob.bot/Gifs/1902.gif",
    "https://cdn.boob.bot/Gifs/1633.gif",
    "https://cdn.boob.bot/Gifs/1948.gif",
    "https://cdn.boob.bot/Gifs/16EB.gif",
    "https://cdn.boob.bot/Gifs/16B0.gif",
    "https://cdn.boob.bot/Gifs/15D5.gif",
    "https://cdn.boob.bot/Gifs/1854.gif",
    "https://cdn.boob.bot/Gifs/17A2.gif",
    "https://cdn.boob.bot/Gifs/18D7.gif",
    "https://cdn.boob.bot/Gifs/163D.gif",
    "https://cdn.boob.bot/Gifs/1720.gif",
    "https://cdn.boob.bot/Gifs/17D1.gif",
    "https://cdn.boob.bot/Gifs/1782.gif",
    "https://cdn.boob.bot/Gifs/1634.gif",
    "https://cdn.boob.bot/Gifs/18CF.gif",
    "https://cdn.boob.bot/Gifs/176C.gif",
    "https://cdn.boob.bot/Gifs/18D8.gif",
    "https://cdn.boob.bot/Gifs/187E.gif",
    "https://cdn.boob.bot/Gifs/173A.gif",
    "https://cdn.boob.bot/Gifs/1742.gif",
    "https://cdn.boob.bot/Gifs/17D0.gif",
    "https://cdn.boob.bot/Gifs/15D0.gif",
    "https://cdn.boob.bot/Gifs/1836.gif",
    "https://cdn.boob.bot/Gifs/16B4.gif",
    "https://cdn.boob.bot/Gifs/169F.gif",
    "https://cdn.boob.bot/Gifs/1954.gif",
    "https://cdn.boob.bot/Gifs/1839.gif",
    "https://cdn.boob.bot/Gifs/1969.gif",
    "https://cdn.boob.bot/Gifs/17E4.gif",
    "https://cdn.boob.bot/Gifs/1989.gif",
    "https://cdn.boob.bot/Gifs/18F4.gif",
    "https://cdn.boob.bot/Gifs/17B4.gif",
    "https://cdn.boob.bot/Gifs/19C3.gif",
    "https://cdn.boob.bot/Gifs/161E.gif",
    "https://cdn.boob.bot/Gifs/162A.gif",
    "https://cdn.boob.bot/Gifs/18BD.gif",
    "https://cdn.boob.bot/Gifs/1659.gif",
    "https://cdn.boob.bot/Gifs/16CB.gif",
    "https://cdn.boob.bot/Gifs/1969.gif",
    "https://cdn.boob.bot/Gifs/1752.gif",
    "https://cdn.boob.bot/Gifs/1709.gif",
    "https://cdn.boob.bot/Gifs/173D.gif",
    "https://cdn.boob.bot/Gifs/1656.gif",
    "https://cdn.boob.bot/Gifs/1884.gif",
    "https://cdn.boob.bot/Gifs/15BD.gif",
    "https://cdn.boob.bot/Gifs/165E.gif",
    "https://cdn.boob.bot/Gifs/1954.gif",
    "https://cdn.boob.bot/Gifs/16FD.gif",
    "https://cdn.boob.bot/Gifs/177C.gif",
    "https://cdn.boob.bot/Gifs/1742.gif",
    "https://cdn.boob.bot/Gifs/189D.gif",
    "https://cdn.boob.bot/Gifs/1797.gif",
  ];

    let result = Math.floor((Math.random() * porngif.length));

    let msg = new Discord.RichEmbed()
    .setTitle(":ok_hand: :sweat_drops:")
    .setImage(porngif[result])
    .setFooter(`Requested by ${message.member.user.tag} at ${message.createdAt.toDateString()}`);

    message.channel.send(msg);



}

module.exports.help = {
  name: "porngif"
}
